print("Day 1 - Python Print Function")
print("The function is declared like this:")
print("print('what to print')")
print("Hello\nGowri\nWelcome")
x="Gowri"+"Mungath"
print(x)
print("Midhun"+" "+"Mungath")
print("Day 1 - String Manipulation")
print('String Concatenation is done with the "+" sign.')
print('e.g. print("Hello " + "world")')
print("New lines can be created with a backslash and n.")
#Let's learn about input function
a=input("what is your name?")
print("Your name is"+a)
print("You are"+input("what is your age?")+" years old.")
